# Generated by Django 3.0.8 on 2020-08-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0003_auto_20200729_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='items',
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=200),
        ),
    ]
